"""initial

Revision ID: 02fe684bacae
Revises: de41436b1746
Create Date: 2025-12-03 14:03:01.156265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02fe684bacae'
down_revision: Union[str, Sequence[str], None] = 'de41436b1746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agendamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_agendada', sa.Date(), nullable=True),
    sa.Column('hora_fim', sa.Time(), nullable=True),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('confirmado_cliente', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agendamentos_id'), 'agendamentos', ['id'], unique=False)
    op.create_table('estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_item', sa.String(), nullable=False),
    sa.Column('quantidade', sa.String(), nullable=False),
    sa.Column('custo_unitario', sa.Float(), nullable=False),
    sa.Column('preco_venda', sa.Float(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('passivo', sa.Boolean(), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('unidade_medida', sa.String(length=50), nullable=True),
    sa.Column('criado_em', sa.Date(), nullable=True),
    sa.Column('atualizado_em', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estoque_id'), 'estoque', ['id'], unique=False)
    op.create_table('horarios_de_trabalho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=False),
    sa.Column('observacao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_horarios_de_trabalho_id'), 'horarios_de_trabalho', ['id'], unique=False)
    op.create_table('orcamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor_sessao', sa.Float(), nullable=False),
    sa.Column('duracao_horas', sa.Time(), nullable=False),
    sa.Column('qtd_sessoes', sa.Integer(), nullable=False),
    sa.Column('enviado_em', sa.DateTime(), nullable=False),
    sa.Column('confirmado_cliente', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orcamentos_id'), 'orcamentos', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('senha_hash', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('expiracao', sa.DateTime(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('remember_me', sa.Boolean(), nullable=True),
    sa.Column('valido', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_table('sessao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=False),
    sa.Column('duracao_horas', sa.Time(), nullable=False),
    sa.Column('data_sessao', sa.DateTime(), nullable=False),
    sa.Column('hora_inicio', sa.DateTime(), nullable=False),
    sa.Column('hora_fim', sa.DateTime(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessao_id'), 'sessao', ['id'], unique=False)
    op.create_table('tatuadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('especialidade', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('capacidade_diaria', sa.Integer(), nullable=True),
    sa.Column('preferencia_turno', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tatuadores_id'), 'tatuadores', ['id'], unique=False)
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tatuador_id', sa.Integer(), nullable=True),
    sa.Column('area_corpo', sa.String(), nullable=False),
    sa.Column('tamanho', sa.String(), nullable=True),
    sa.Column('imagem_png', sa.String(), nullable=True),
    sa.Column('coordenadas', sa.Text(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('solicitado', 'aguardando_orcamento', 'aguardando_confirmacao', 'confirmado', 'finalizado', 'cancelado', name='statuspedido'), nullable=False),
    sa.Column('agendamento_id', sa.Integer(), nullable=True),
    sa.Column('sessao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agendamento_id'], ['agendamentos.id'], ),
    sa.ForeignKeyConstraint(['sessao_id'], ['sessao.id'], ),
    sa.ForeignKeyConstraint(['tatuador_id'], ['tatuadores.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_id'), 'pedidos', ['id'], unique=False)
    op.create_table('todos_os_horarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tatuador_id', sa.Integer(), nullable=True),
    sa.Column('horario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['horario_id'], ['horarios_de_trabalho.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tatuador_id'], ['tatuadores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todos_os_horarios_id'), 'todos_os_horarios', ['id'], unique=False)
    op.create_table('venda_consumivel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('preco_final', sa.Float(), nullable=True),
    sa.Column('pedidos_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['estoque.id'], ),
    sa.ForeignKeyConstraint(['pedidos_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venda_consumivel_id'), 'venda_consumivel', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venda_consumivel_id'), table_name='venda_consumivel')
    op.drop_table('venda_consumivel')
    op.drop_index(op.f('ix_todos_os_horarios_id'), table_name='todos_os_horarios')
    op.drop_table('todos_os_horarios')
    op.drop_index(op.f('ix_pedidos_id'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_tatuadores_id'), table_name='tatuadores')
    op.drop_table('tatuadores')
    op.drop_index(op.f('ix_sessao_id'), table_name='sessao')
    op.drop_table('sessao')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_orcamentos_id'), table_name='orcamentos')
    op.drop_table('orcamentos')
    op.drop_index(op.f('ix_horarios_de_trabalho_id'), table_name='horarios_de_trabalho')
    op.drop_table('horarios_de_trabalho')
    op.drop_index(op.f('ix_estoque_id'), table_name='estoque')
    op.drop_table('estoque')
    op.drop_index(op.f('ix_agendamentos_id'), table_name='agendamentos')
    op.drop_table('agendamentos')
    # ### end Alembic commands ###
